### ISSUE TITLE
where can i find gtags?

### ISSUE THREAD

**Issue by gitrj95** [Ergus/gtags-mode#2]
the executable that i was able to fetch from https://www.gnu.org/software/global/ fails on linking. is there a stable exe for gtags floating around that you are using?

**Comment by Ergus** [comment]
Hi:
Normally I use `global` /`gtags` from my linux distribution but it seems you are on windows (because you request for an exe file). If that's the case I can't help you more than the link in the web [gtags win32](http://adoxa.altervista.org/global/dl.php?f=win32) because I don't use windows since almost a decade.

But if you send a message to the gtags developer, the [Mailing list](https://www.gnu.org/software/global/maillist.html), or to the win32 exe creator[Jason Hood](mailto:jadoxa@yahoo.com.au?subject=GLOBAL) I am pretty sure you will get some help.

Best,
Ergus

**Comment by gitrj95** [comment]
sorry, i didn't mean to imply i'm a windows user :). i work with unix-like OS through and through. i tried building from source and it failed

**Comment by gitrj95** [comment]
i was able to build and link on a previous version. weird. anyways, not related to this. although, i have found an interesting bug. i am on macOS and remoting into a server via TRAMP, and when i try to create the tag metadata via gtags-mode-create, the path for the gtags binary is the local one, not the remote. i don't think this is a bug with your mode, though

**Comment by Ergus** [comment]
> i was able to build and link on a previous version. weird. anyways, not related to this. although, i have found an interesting bug. i am on macOS and remoting into a server via TRAMP, and when i try to create the tag metadata via gtags-mode-create, the path for the gtags binary is the local one, not the remote. i don't think this is a bug with your mode, though

Actually my package tries very hard to find gtags/global remotely. You could try:
```
M-: (executable-find "gtags" t)
```
In your remote file this must return the path of global in the remote machine. Else it means that tramp can't find the remote executable... two possibilities here:

1. global is not in the remote path. remember that tramp don't load the bashrc, you need to use the .profile)
2. You set it in your path with profile, but tramp don't search 
in your local variables of remote hosts... you may need to add: `(add-to-list 'tramp-remote-path 'tramp-own-remote-path)` in your config

**Comment by gitrj95** [comment]
thanks. i'll check these out

**Comment by gitrj95** [comment]
neither appears to work. i have a feeling this is some nuance wrt using TRAMP from macOS. if i find something useful, i'll lyk here. eg, executable-find yields my local path, even with tramp up. this is consistent whether i use my config, add tramp-remote-path to the head as above, or use emacs -Q

**Comment by Ergus** [comment]
The executable-find command works??

**Comment by gitrj95** [comment]
yes. it works, and it points to the wrong place. concretely, it points to my opt/homebrew/<foo> location, and not my /usr/bin/<goo> location

**Comment by Ergus** [comment]
> yes. it works, and it points to the wrong place. concretely, it points to my opt/homebrew/ location, and not my /usr/bin/ location

Then it may be a problem with tramp? If that's the case could you submit an issue in the emacs mailing list or the bug tracker? So Michael can take care of it?
