### ISSUE TITLE
gtags-mode is kinda spammy in the echo area

### ISSUE THREAD

**Issue by mx** [Ergus/gtags-mode#4]
It might be a difference in tastes, but it gtags-mode is really liberal in what it outputs to the echo area. Create a new structure in a file and save it, and gtags will immediately tell you that it ran global --single-update. This feels more like a debug message than something for the user. Could a customizable variable be added to turn these messages off?

**Comment by Ergus** [comment]
Hi @mx :

These messages were a design choice on the beginning. Remember that the main goal of `gtags-mode` was to be simple in code and customization; and such messages are actually very useful to handle errors specially when the users are not very experienced and report weird bugs. Many similar package use the same approach when they depend of external tools but want to offer more or less a transparent final user experience.

That said, merge request are very welcome ;)
